import "./globals.css";
import { Space_Grotesk } from "next/font/google";




const space = Space_Grotesk({ subsets: ["latin"] })

export const metadata = {
  title: {
    template: "%s | Elite Essentialz ",
    default: "Elite Essentialz"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${space.className} min-h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
